version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: monitor
      POSTGRES_PASSWORD: monitorpass
      POSTGRES_DB: monitor
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://monitor:monitorpass@db:5432/monitor?schema=public"
      TELEGRAM_TOKEN: "<PUT_YOUR_TOKEN>"
      TELEGRAM_CHAT_ID: "<CHAT_ID>"
      PORT: "3000"
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app

volumes:
  db-data:
